screenshots/wineries.png:
	depict http://www.nytimes.com/interactive/2013/07/07/business/a-nation-of-wineries.html  -s '#main' $@

screenshots/japan.png:
	depict http://www.nytimes.com/interactive/2011/03/13/world/asia/satellite-photos-japan-before-and-after-tsunami.html  -s '#main' $@

screenshots/weightlifting.png:
	depict http://www.nytimes.com/interactive/2012/08/07/sports/olympics/weighlighting.html  -s '#main' $@

screenshots/inauguration.png:
	depict http://www.nytimes.com/packages/html/politics/20130121-inauguration/obama-inauguration-zoomer-2013.html  -s 'body' $@

screenshots/gestures.png:
	depict http://www.nytimes.com/interactive/2013/07/01/world/europe/A-Short-Lexicon-of-Italian-Gestures.html?ref=europe  -s '#main' $@

screenshots/quietmap.png:
	depict http://www.nytimes.com/newsgraphics/2013/quiet/?hp#/map/  -s 'body' $@

screenshots/donors.png:
	depict http://www.nytimes.com/interactive/2012/04/15/us/politics/Access-in-Washington-Rises-With-Donation-Size.html?ref=politics  -s 'body' $@
